#!/usr/bin/env bash
# Generate the supercronic crontab from channels.conf — one line per channel.
# Output goes to ops/scheduler/crontab (a generated, gitignored artifact; edit
# channels.conf, not the crontab). `make scheduler-up` runs this for you.
set -euo pipefail
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=ops/scheduler/lib.sh
source "$DIR/lib.sh"

OUT="${1:-$DIR/crontab}"

{
  echo "# GENERATED by ops/scheduler/gen-crontab.sh from channels.conf — DO NOT EDIT."
  echo "# Edit ops/scheduler/channels.conf, then: make scheduler-restart"
  echo "# Times are in the container TZ (SCHEDULER_TZ in .env; default Etc/GMT+5)."
  echo "#"
  echo "# min hour dom mon dow   command"
  while IFS=$'\t' read -r channel count delay tier cron; do
    printf '%s   /app/ops/scheduler/run-daily.sh %s %s %s %s >> /app/data/daily.log 2>&1\n' \
      "$cron" "$channel" "$count" "$delay" "$tier"
  done < <(sched_rows)
  echo "#"
  echo "# Watchdog: sleep/wake resumes containers without a boot, so boot-time"
  echo "# catch-up never fires after a wake. This re-checks every 20 min (minute"
  echo "# 13/33/53 — off the :00/:30 fire minutes) and posts only the shortfall."
  echo '13,33,53 * * * *   /app/ops/scheduler/catch-up.sh watchdog >> /app/data/daily.log 2>&1'
} > "$OUT"

echo "wrote $OUT:" >&2
grep -vE '^\s*#|^\s*$' "$OUT" | sed 's/^/  /' >&2
